-- data in the `coffee_shop` dataset¹ comes from our sales system
{{ config(materialized='table') }}


SELECT Person_SK,
       FullName,
       Prefix,
       PreferredFirstName,
       FirstName,
       MiddleName,
       LastName,
       Suffix,
       PreferredPronoun,
       PreviousFirstName,
       PreviousLastName,
       MaritalStatus,
       Gender,
       CurrentAge,
       IsConfidentialRecord,
       IsDeceased,
       DeceasedDate,
       CitizenshipStatus,
       IsUnitedStatesCitizen,
       IsNonResidentAlien,
       CitizenshipCountry,
       ImmigrationStatus,
       BirthCountry,
       IsMilitaryAffiliated,
       MilitaryStatus,
       MilitaryBranch,
       MilitaryTuitionAssistanceCode,
       MilitaryTuitionAssistanceEndDate,
       MilitaryVeteranAffairsBenefitCode,
       MilitaryVeteranAffairsBenefitEndDate,
       IsActiveMilitary,
       IsMilitarySpouse,
       PreferredContactMethod,
       PreferredAppointmentTime,
       HasOptedOutOfEmail,
       DoNotPhone,
       DWCreated,
       DWModified,
       IsFrozenRecord,
       BirthCountryCode,
       MilitaryTuitionAssistance,
       MilitaryVeteranAffairsBenefit,
       RecordedEthnicity,
       GenderIdentity,
       AdmissionCounselor_SK,
       CareerStatus,
       HasReceivedReleasedFERPA,
       IsEmployed,
       LastFirstName,
       HasEmployeeTuitionBenefit,
       HasOptedOutOfFax,
       HasOptedOutOfCall,
       UnifyUserRole,
       UnifyUserProfile,
       GenderCode,
       TaxIdentificationNumber,
       HasPrivacyRestriction FROM  SNM.EDW_dbo_DimPerson